#!/bin/bash
export QT_IM_MODULE=${QT_IM_MODULE:-fcitx}
export XMODIFIERS=${XMODIFIERS:-@im=fcitx}
BINDS_LIST="$HOME/.config/wps-bwrap/binds.list"
exe=$(basename $BASH_SOURCE)

binds=()
for dir in fontconfig gtk-2.0 gtk-3.0 gtk-4.0 kingsoft Kingsoft; do
    if [ ! -d ~/.config/"$dir" ]; then mkdir ~/.config/"$dir"; fi
    binds+=(--bind ~/.config/"$dir" ~/.config/"$dir")
done

if [ -e ~/.config/mimeapps.list ]; then
    binds+=(--bind ~/.config/mimeapps.list ~/.config/mimeapps.list)
fi

if [ ! -d ~/.local/share/Kingsoft ]; then mkdir -p ~/.local/share/Kingsoft; fi
binds+=(--bind ~/.local/share/Kingsoft ~/.local/share/Kingsoft)
#binds+=(--bind ~/tmp/ ~/tmp/)

DOC_DIR=$(xdg-user-dir DOCUMENTS)
binds+=(--bind $DOC_DIR $DOC_DIR)

DOWN_DIR=$(xdg-user-dir DOWNLOAD)
binds+=(--bind $DOWN_DIR $DOWN_DIR)

PIC_DIR=$(xdg-user-dir PICTURES)
binds+=(--bind $PIC_DIR $PIC_DIR)

if [[ -f "$BINDS_LIST" ]]; then
    for p in $(cat "$BINDS_LIST"); do
        if [ -e "$p" ]; then
            binds+=(--bind "$p" "$p")
        fi
    done
fi

#bind mount 需要操作的文件
file=$1
if [[ -f "$file" ]]; then
    path="$(realpath "$file")"
    binds+=(--bind "$path" "$path")
fi
# args=()
# for arg in "$@"; do
#     # 去掉 file:// 前缀（如果有）
#     path="${arg#file://}"
#     fname=$(realpath "$path")
#     binds+=(--bind "$fname" "$fname")
#     args+=("${fname##*/}")
# done

exec bwrap --unshare-all --share-net --die-with-parent \
    --ro-bind / / \
    --tmpfs /sys --tmpfs /home --tmpfs /tmp --tmpfs /run --proc /proc --dev /dev \
    --ro-bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
    --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
    "${binds[@]}" \
    "/opt/kingsoft/wps-office/office6/bin/$exe" "$@"
    # "/opt/kingsoft/wps-office/office6/wps" "${args[@]}"
